### ISSUE TITLE
Script not working correctly with (at least?) 2 threads

### ISSUE THREAD

**Issue by wideocean** [buxlover/autobump#1]
I have modified the data.json as described.

Excerpt of data.json:

"threads": [{
        "url": "https://bitcointalk.org/index.php?topic=1XXXXXX"
    },{
    "url": "https://bitcointalk.org/index.php?topic=1XXXXXX"
}]

So my setup is:
- 2 threads
- new account for bumping (<10 activity)

The procedure I did:
1. run:
   -> data.json UNCHANGED
   -> 1. thread: bump
   -> 2. thread: no bump
   => bump behavior is correct but data.json was not modified somehow

WAIT 7 minutes (new accounts need to wait 360 secs between each post, I waited 7 mins just to be sure)
1. run:
   -> data.json CHANGED
   -> 1. thread: no bump (initial bump from 1. run ofc is still there) + lastActivityAt
   -> 2. thread: bump + lastActivityAt + lastBumpURL
   => data.json changed accordingly now except lastBumpUrl for 1. thread is missing
2. run:
   -> data.json UNCHANGED
   -> 1. thread: last post >24h
   -> 2. thread: last post <24h 
   => Script runs, nothing happens, no bumps
3. run:
   -> data.json UNCHANGED
   -> 1. thread: last post >24h -> bump
   -> 2. thread: last post >24h -> no bump
   => still no lastBumpURL on 1. thread, therefore ofc 1. bump was not deleted
# 

So the thing is...
1) the lastBumpUrl is not being added to the 1. thread for unknown reason. And because of that it does not delete the old bumps from the 1. thread.
2) from the 3. run, we can see that the script somehow does not bump to the 1. thread even though the last post is older than 24 hours. According to the script, it should have bumped the first thread independent of the 2. thread. But somehow it first bumps when both threads are 'bumpable'.

Just wanted to report my issues. Technically, for each thread I can run one instance of the script to avoid this whole issue but yeah, just wanted to report the issue.
Unfortunately, I cannot reproduce this with 3, 4, ... threads cause I only have 2 threads.

**Comment by buxlover** [comment]
Thank you for your detailed report on the problem 👍 
I'll look into the issue asap

**Comment by buxlover** [comment]
@WideOcean Code has been updated with a function named `isError()`. If you are getting same issue again, just try to post the error_log file here so that I can analyze the cause and fix it.

**Comment by wideocean** [comment]
@buxlover Thank you for tackling the issue and updating the code.
I want to share with you my test results again. Between the runs, I waited at least 6 minutes unless I explicitly stated otherwise

23.10.2016

RUN 1:
1. thread: bump + lastActivityAt + lastbumpURL
2. thread: no bump + lastActivityAt
=> NOTE: lastBumpURL is the URL referencing post #1 of thread
    => Is it supposed to be like that? Intuitively, I would think it should be the URL of the 'bump' post directly
=> nevertheless, **correct behaviour**

RUN 2:
1. thread: no bump (initial bump from 1. run ofc is still there) + lastActivityAt + lastbumpURL
2. thread: bump + lastActivityAt + lastBumpURL
=> NOTE: lastBumpURL is the URL referencing post #1 of thread
=> **correct behaviour**

RUN 3:
nothing happens (BLANK SCREEN)
=> **correct behaviour**

**_WAIT 24+ hours_**

RUN 4:
1. thread: bump
2. thread: no bump
=> **correct behaviour**
=> but also **ERROR**: 

> Notice: Undefined variable: posts in C:\Users\Administrator\Desktop\UniServerZ\www_bump\functions.php on line 263
> Notice: Trying to get property of non-object in C:\Users\Administrator\Desktop\UniServerZ\www_bump\functions.php on line 365

**_WAIT 3!!! minutes_**

RUN 5:
1. thread: unchanged
2. thread: old bump deleted
=> **old bump should NOT be deleted yet**
=> BLANK SCREEN WITH **ERROR**

> Notice: Undefined variable: posts in C:\Users\Administrator\Desktop\UniServerZ\www_bump\functions.php on line 263
> Putting Bump
> 
> Notice: Trying to get property of non-object in C:\Users\Administrator\Desktop\UniServerZ\www_bump\functions.php on line 365

**_WAIT another 3 minutes (so 6 minutes now since 4. run)_**

RUN 6:
1. thread: unchanged
2. thread: bump
=> **correct behaviour**
=> **ERROR**:

> Notice: Undefined variable: posts in C:\Users\Administrator\Desktop\UniServerZ\www_bump\functions.php on line 263
> Putting Bump
> 
> Notice: Trying to get property of non-object in C:\Users\Administrator\Desktop\UniServerZ\www_bump\functions.php on line 365

# 

Well the code works correct all in all. The only thing to be resolved is the too early deletion of the bump. Right now it checks if last bump is older than 24 hours and delete it. Better would be to only delete it when it also can bump in same run.
And the error messages should be reviewed again, although that's more lower priority I guess cause script is working fine mainly.
Well to summarize, script is working fine now. The early deletion of the bump can be avoided by setting an appropriate cron interval and the error notices don't seem to affect the bumping behaviour as far as I can tell. Thank you for updating the code. Feel free to update it further if you want.

Here an excerpt of the error log:

```
[Sun Oct 23 17:52:12.578200 2016] [:error] [pid 780:tid 1492] [client ::1:56543] PHP Notice:  Trying to get property of non-object in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 365
[Mon Oct 24 18:01:36.200800 2016] [:error] [pid 780:tid 1472] [client ::1:57958] PHP Notice:  Undefined variable: posts in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 263
[Mon Oct 24 18:01:42.117800 2016] [:error] [pid 780:tid 1472] [client ::1:57958] PHP Notice:  Trying to get property of non-object in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 365
[Mon Oct 24 20:01:36.483000 2016] [:error] [pid 780:tid 1472] [client ::1:59417] PHP Notice:  Undefined variable: posts in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 263
[Mon Oct 24 20:01:41.966600 2016] [:error] [pid 780:tid 1472] [client ::1:59417] PHP Notice:  Trying to get property of non-object in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 365
[Tue Oct 25 18:03:46.383400 2016] [:error] [pid 780:tid 1480] [client ::1:60411] PHP Notice:  Undefined variable: posts in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 263
[Tue Oct 25 18:03:53.158400 2016] [:error] [pid 780:tid 1480] [client ::1:60411] PHP Notice:  Trying to get property of non-object in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 365
[Tue Oct 25 18:21:08.200600 2016] [core:warn] [pid 2844:tid 168] AH00098: pid file C:/Users/Administrator/Desktop/UniServerZ/core/apache2/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Oct 25 18:21:08.221600 2016] [mpm_winnt:notice] [pid 2844:tid 168] AH00455: Apache/2.4.23 (Win32) PHP/7.0.11 configured -- resuming normal operations
[Tue Oct 25 18:21:08.221600 2016] [mpm_winnt:notice] [pid 2844:tid 168] AH00456: Apache Lounge VC14 Server built: Jul  1 2016 11:09:37
[Tue Oct 25 18:21:08.221600 2016] [core:notice] [pid 2844:tid 168] AH00094: Command line: 'C:\\Users\\Administrator\\Desktop\\UniServerZ\\core\\apache2\\bin\\httpd_z.exe -d C:/Users/Administrator/Desktop/UniServerZ/core/apache2 -f C:\\Users\\Administrator\\Desktop\\UniServerZ\\core\\apache2\\conf\\httpd.conf -d C:\\Users\\Administrator\\Desktop\\UniServerZ\\core\\apache2'
[Tue Oct 25 18:21:08.222600 2016] [mpm_winnt:notice] [pid 2844:tid 168] AH00418: Parent: Created child process 2264
[Tue Oct 25 18:21:08.486600 2016] [mpm_winnt:notice] [pid 2264:tid 284] AH00354: Child: Starting 150 worker threads.
[Wed Oct 26 23:33:34.146400 2016] [:error] [pid 2264:tid 1496] [client ::1:59577] PHP Notice:  Undefined variable: posts in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 263
[Wed Oct 26 23:33:40.241200 2016] [:error] [pid 2264:tid 1496] [client ::1:59577] PHP Notice:  Trying to get property of non-object in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 365
[Wed Oct 26 23:33:41.879200 2016] [:error] [pid 2264:tid 1496] [client ::1:59577] PHP Notice:  Undefined variable: posts in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 263
[Wed Oct 26 23:33:45.888400 2016] [:error] [pid 2264:tid 1496] [client ::1:59577] PHP Notice:  Trying to get property of non-object in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 365
[Wed Oct 26 23:37:02.436400 2016] [:error] [pid 2264:tid 1496] [client ::1:59860] PHP Notice:  Undefined variable: posts in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 263
[Wed Oct 26 23:37:03.341200 2016] [:error] [pid 2264:tid 1496] [client ::1:59860] PHP Notice:  Trying to get property of non-object in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 365
[Wed Oct 26 23:40:34.842200 2016] [:error] [pid 2264:tid 1496] [client ::1:60234] PHP Notice:  Undefined variable: posts in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 263
[Wed Oct 26 23:40:36.339800 2016] [:error] [pid 2264:tid 1496] [client ::1:60234] PHP Notice:  Trying to get property of non-object in C:\\Users\\Administrator\\Desktop\\UniServerZ\\www\\_bump\\functions.php on line 365
```

**Comment by buxlover** [comment]
@WideOcean LOL mate. It was funny. Error is being raised when I try to find whether there's been any error. I'll get back to these codes this weekend and update the code 😎

**Comment by buxlover** [comment]
There  have been bugs with function isError() and deleting bump's. It should work now (I believe 😈 )
