### ISSUE TITLE
Error when running script twice successively with new account

### ISSUE THREAD

**Issue by wideocean** [buxlover/autobump#2]
If you use a new bitcointalk account with still very low activity count for bumping, and let's say you have 2 threads so you want to bump both threads one after another, then an error message is thrown.

Error:

> Notice: Undefined variable: posts in C:\Users\Administrator\Desktop\UniServerZ\www_bump\functions.php on line 260
> Putting Bump
> 
> Notice: Undefined offset: -1 in C:\Users\Administrator\Desktop\UniServerZ\www_bump\functions.php on line 113
> 
> Fatal error: Uncaught Error: Call to a member function find() on null in C:\Users\Administrator\Desktop\UniServerZ\www_bump\functions.php:115 Stack trace: #0 C:\Users\Administrator\Desktop\UniServerZ\www_bump\functions.php(242): getPosts('<!DOCTYPE html ...', 'https://bitcoin...', true) #1 C:\Users\Administrator\Desktop\UniServerZ\www_bump\cron.php(29): bumpIt(Resource id #6, 'https://bitcoin...') #2 {main} thrown in C:\Users\Administrator\Desktop\UniServerZ\www_bump\functions.php on line 115

I guess because new accounts have a limit regarding post requests.
If you post in a thread and want to post in another thread right after, it says on the Bitcointalk website that you have to wait 360 seconds before next post.
I think that this might have something to do with why the error message comes up but I'm not sure.
Either way, it would be good if that error can be caught and you print out nothing or simple message to user.

**Comment by buxlover** [comment]
I  think it's been solved. If anyone can test it and  get me result, that'd be awesome 👍
